### ISSUE TITLE
how to set the initial filter value?

### ISSUE THREAD

**Issue by level20peon** [denyssene/SimpleKalmanFilter#14]
I would like to set an inital filter value (an assumed current value to use as a starting point that is not 0) - how is this possible with your library?

**Comment by Olejan** [comment]
I have same issue. I use bmp180 module to get pressure. Pressure can change very quick (module set on a drone). Range of pressure is 1015.00 - 1000.00 mBar. And I do not know how to configure my filter to get filtered measure of pressure. If I configure filter like (1, 1, 0.01) like in altitude example my filtered pressure will change very slow. But I need quick change, because my bmp180 module set on a drone.
Question: how to configure SimpleKalmanFilter? What is the method to configure it?

**Comment by Olejan** [comment]
> I would like to set an inital filter value (an assumed current value to use as a starting point that is not 0) - how is this possible with your library?

Look at [Base usage](https://github.com/denyssene/SimpleKalmanFilter?tab=readme-ov-file#basic-usage)

**Comment by denyssene** [comment]
Provide the correct values when instantiating the class.

**Comment by level20peon** [comment]
Could you please provide an example?
